import type { Metadata } from "next";
import "@/scss/main.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocalLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body>
        <div className="body-inner">
          <Header />
          <main className="main-content pt-[108px]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
