import type { Metadata } from "next";
import "@/scss/main.scss";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="main-content pt-[108px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
